# Funding and contact options for this open-source project
# IoT-based  & Offline System

github: [chetanngavali]

custom:
  - https://chetanngavali.com.de/contact
  - https://www.linkedin.com/in/chetanngavali
  - https://github.com/chetanngavali
